#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Monitor Layout
## 1 Monitor
#bspc monitor -d I II III IV V VI VII VIII IX X
## 2 Monitors
bspc monitor eDP -d I II III IV V
bspc monitor HDMI-A-0 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Start up

## Background
feh --bg-fill /home/justasteri/Pictures/weeb_pc.jpg

## Polybar
~/.config/polybar/./launch.sh
~/.config/polybar/./launch2.sh


# Mouse
bspc config focus_follows_pointer true

picom --experimental-backends &
bspc config border_width 0
